### ISSUE TITLE
Add the ability to pass additional columns through to opportunity 

### ISSUE THREAD

**Issue by jcbmllgn** [fivetran/dbt_salesforce_source#1]
We have several custom columns on Opportunity in Salesforce that we would like to make available downstream on [opportunity_enhanced](https://github.com/fivetran/dbt_salesforce/blob/master/models/salesforce_opportunity_enhanced.sql#L4). 

See [this Segment package PR](https://github.com/fishtown-analytics/segment/pull/19) for an example of how the dbt community has done this elsewhere.

**Comment by fivetran-kristin** [comment]
This has been added! :)
