### ISSUE TITLE
BUG - dbt Hub version not up to date

### ISSUE THREAD

**Issue by rcaddell** [fivetran/dbt_salesforce_source#12]
**Are you a current Fivetran customer?** 
Randy Caddell - BI Architect - NWN Carousel (formerly Carousel Industries)

**Describe the bug**
The Salesforce_source package on the dbt hub site is still set to v0.2.2, which has a limit with the version of Fivetran_Utils.  This looks to be corrected in v0.3.0

**Steps to reproduce**
Add fivetran/fivetran_log package to project
Add fivetran/marketo package to project
run dbt deps, profit
add fivetran/salesforce package to project
run dbt clean (just for good measure)
run dbt deps, error on the second range of acceptable versions for fivetran_utils, the second having a cap of 0.2.0 which matches the packages yml of salesforce_source v0.2.2

**Expected behavior**
All packages should install correctly

**Project variables configuration**
# Package Variables
vars:
  marketo_source:
    marketo_database: pc_fivetran_db
    marketo_schema: marketo
  fivetran_log:
    fivetran_log_database: pc_fivetran_db
    fivetran_log_schema: fivetran_log

**Package Version**
packages:
  - package: fivetran/fivetran_log
    version: 0.4.0
  - package: fivetran/marketo
    version: 0.5.0
  - package: fivetran/salesforce
    version: 0.3.1
  - package: dbt-labs/dbt_utils
    version: 0.7.0
**Warehouse**

 
- [ ] BigQuery
- [ ] Redshift
- [ x] Snowflake
- [ ] Postgres
- [ ] Databricks
- [ ] Other (provide details below)

**Additional context**
 

**Screenshots**

**Please indicate the level of urgency** 
Not critical for us as we are just testing the Salesforce package on a more vanilla Force instance we have, however, I imagine this may impact others.

**Are you interested in contributing to this package?** 

- [ ] Yes, I can do this and open a PR for your review.
- [ ] Possibly, but I'm not quite sure how to do this. I'd be happy to do a live coding session with someone to get this fixed. 
- [ ] No, I'd prefer if someone else fixed this.  I don't have the time and/or don't know what the root cause of the problem is.
- [ X] You already have this fixed in the main branch (v0.3.0) it just need to be updated on the actual dbt hub site I believe

**Comment by fivetran-joemarkiewicz** [comment]
Hi @rcaddell thanks for creating this Issue! We are currently aware that the version on the dbt hub is not up to date yet. We are able to see that the PR is open on the dbt hub, but has not been merged yet.

I just reached out to dbt-labs to see how we can merge this [PR](https://github.com/dbt-labs/hub.getdbt.com/pull/742) to officially upgrade this package. Once this version is live on the hub we will be able to cut the release for the transformation package. I will be sure to post back here once both are live on the hub!

**Comment by fivetran-joemarkiewicz** [comment]
@rcaddell both the source and transform latest releases are now live on the [dbt hub](https://hub.getdbt.com/fivetran/salesforce/latest/) which incorporate dbt 0.20.0 compatibility and will work alongside the latest releases of the fivetran log and marketo packages.

We are currently updating our remaining packages so if you are looking to use another Fivetran package alongside these then you may need to wait a few days until all our packages are updated for dbt 20 compatibility. Thanks!
