### ISSUE TITLE
FEATURE - History Mode Compatibility

### ISSUE THREAD

**Issue by fivetran-joemarkiewicz** [fivetran/dbt_salesforce_source#13]
**Are you a Fivetran customer?** 

Yes, @jcbmllgn from Firefly health

**Is your feature request related to a problem? Please describe.**
 
No related problem, just a feature improvement request.

**Describe the solution you'd like**
 
Fivetran has recently included a history mode (beta) to several Salesforce tables. It would be a good feature to build out history mode compatibility with this package.

**Describe alternatives you've considered**
 
A user would need to manually modify the package contents to ensure duplicates from the history mode are not included in the query results.

**Additional context**

If a user turns history mode on for the current tables this package supports then there will be duplicates. We will want to build out functionality that allows a user to "turn on" history mode which will filter out historical records and just retain the current fields.

**Please indicate the level of urgency and business impact of this request** 

Moderate urgency. We should be able to pick this up during the next sprint.

**Are you interested in contributing to this package?** 

- [ ] Yes, I can do this and open a PR for your review.
- [ ] Possibly, but I'm not quite sure how to do this. I'd be happy to do a live coding session with someone to get this work implemented. 
- [X] No, I'd prefer if someone else did this.  I don't have the time and/or don't know how to incorporate the changes necessary.

**Comment by jcbmllgn** [comment]
Thanks for creating the ticket @fivetran-joemarkiewicz !

**Comment by fivetran-joemarkiewicz** [comment]
@jcbmllgn the `v0.3.1` release of this package was just cut and is live on the [dbt hub](https://hub.getdbt.com/fivetran/salesforce_source/latest/). Be sure to take a look at the release notes to see the variables being used for the history mode feature of filtering out records.

Please also reopen this ticket if you have any questions related to the issue after you turn history mode on. Thanks!
