### ISSUE TITLE
User role table not present

### ISSUE THREAD

**Issue by elvisace** [fivetran/dbt_salesforce_source#5]
Hey guys, thanks for the package!

I'm seeing this sql error when trying to use it:
```
SQL compilation error:
  Object 'DB_NAME.SALESFORCE.USER_ROLE' does not exist or not authorized.
  compiled SQL at target/run/salesforce_source/models/tmp/stg_salesforce__user_role_tmp.sql
```

When I look at snowflake, I don't see a `USER_ROLE` table, and when I go to fivetran and look at the schema for available tables, I also don't see a user_role table (or anything that looks like it).

Are there different salesforce connectors or is this package out of date with the current salesforce connector in fivetran?

**Comment by elvisace** [comment]
I am not using the salesforce marketing cloud connector

**Comment by fivetran-kristin** [comment]
Hey @elvisace - this package uses our Fivetran salesforce connector [here](https://fivetran.com/docs/applications/salesforce).

Two questions for you:
1. Do you use the [user role functionality](https://help.salesforce.com/articleView?id=sf.users_role_view.htm&type=5) in Salesforce?
2. Do you have all tables from Salesforce selected to sync? This can be found in the "Schema" section of your Fivetran connector details.

**Comment by fivetran-kristin** [comment]
Hey @elvisace - Just wanted to check in here. Please let me know.

**Comment by fivetran-kristin** [comment]
Closing this issue for now, if issue persists please reopen.
